### ISSUE TITLE
try to add cat-list component to my bit.dev account

### ISSUE THREAD

**Issue by tomokat** [tomokat/cat-components#5]

**Comment by tomokat** [comment]
added [stencil compiler 0.0.35](https://bit.dev/bit/envs/compilers/stencil) but got error:

```
Error: Cannot find module '@stencil/sass' Require stack: -
           /tmp/bit/capsule-26252/stencil.config.ts -
           /home/user/git/cat-components/node_modules/@stencil/core/compiler/stencil.js
           -
           /home/user/git/cat-components/node_modules/@stencil/core/sys/node/index.js
           -
           /home/user/git/cat-components/node_modules/@stencil/core/bin/stencil
           at Function.Module._resolveFilename
           (internal/modules/cjs/loader.js:965:15) at Function.Module._load
           (internal/modules/cjs/loader.js:841:27) at Module.require
           (internal/modules/cjs/loader.js:1025:19) at require
           (internal/modules/cjs/helpers.js:72:18) at Object.<anonymous>
           (/tmp/bit/capsule-26252/stencil.config.ts:4:16) at Module._compile
           (internal/modules/cjs/loader.js:1137:30) at
           Object.require.extensions..ts
           (/home/user/git/cat-components/node_modules/@stencil/core/compiler/stencil.js:62907:16)
           at Module.load (internal/modules/cjs/loader.js:985:32) at
           Function.Module._load (internal/modules/cjs/loader.js:878:14) at
           Module.require (internal/modules/cjs/loader.js:1025:19)

    at makeError (/home/user/git/cat-components/.git/bit/components/compilers/stencil/bit.envs/0.0.35/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/user/git/cat-components/.git/bit/components/compilers/stencil/bit.envs/0.0.35/node_modules/execa/index.js:114:26)
```

looks like this compiler was built for stencil 1.10.0 or above but might not be compatible with 2.0?

**Comment by tomokat** [comment]
I need to find a way to fork current stencil compiler as it was throwing some error.
[Some of the detail is captured within this github issue I created on their repo](https://github.com/teambit/bit/issues/3103)

[Link to bit.dev with my cat-list component finally rendered](https://bit.dev/teamcat/catcomponents/cat-list)
